---
title: "初心者セッションになる予定だった何か"
author: "あきる（paithiov909）"
lang: ja
format:
  revealjs:
    transition: fade
    slide-number: "c/t"
    overview: true
    chalkboard: false
    progress: true
    history: false
    theme: [default, slides.scss]
    include-in-header: header.html
    embed-resources: true
---

## この資料について

- これは[TokyoR #112](https://tokyor.connpass.com/event/312792/)の資料になる予定だった何かです
- RStudioを使い始めた初心者向けの情報を話します

## 初心者のツライところ

- 「**課題を解決するために、何をどう調べたらいいのかわからない！**」
- そこで、このセッションでは
  - 「Rについて勉強したいならこのあたりを読んでおくといいよ」という資料をいくつか提示します
  - Rを練習していくうえで「Rについての情報」を調べるコツを教えます

## R/RStudioのインストールの方法

- 「[私たちのR](https://www.jaysong.net/RBook/)」を読んでおけばOK
  - 恐れずに「はい（Yes）」とか「次へ（next）」とかをポチポチしていけばインストールできる
  - 4月25日くらいにRのv4.4.0がリリース予定なので注意

## 「Rの基礎」を勉強するには

- 「変数に値を代入する」「データにはいくつかの種類の型がある」「演算子とか制御構文とかいうやつがある」「関数のつくり方・呼び出し方について」みたいなことは、**好みの教科書や資料を読んで勉強するとよい**
    - このへんは「[私たちのR](https://www.jaysong.net/RBook/)」にも書かれているので、そのあたりを一通り読むのでもよい
  - 英語が得意なら「[Deep R Programming](https://deepr.gagolewski.com)」や「[Advanced R](https://adv-r.hadley.nz/)」の前半のほうを読むのもオススメ

## Rでわからないことの調べ方

- 「○○という分析をおこなうための××パッケージの△△という関数の使い方がわからない」
  - こういう場合は、慣れてくれば自分で調べられる。資料やヘルプを読んだり、ChatGPTとかに質問してもいい
- 「既存の関数にデータを突っ込むために、読み込んだデータをその関数が受け付けるかたちに加工しなければいけないんだけど、謎のエラーが出てよくわからない」
  - こういう場合のほうが、初心者だととくに大変

## 何がわからないのかを特定する

- コードを修正するためには、はじめに解決したい課題を特定するスキルが必要
  - どこがおかしいのか当たりをつける
  - どのようにおかしいのか当たりをつける
- 解決したい課題が特定できたら、あとはAIや人に質問しちゃってもいい

## 実際のデバッグの例

例として、次のような見た目のデータが「カンマ区切りの文字列」として手もとにあったとして、 3列目の最大値（ここでは`12`になるはず）を返す関数を書きたいとする

| ① | ② | ③ |
|-----|-----|-----|
| 10 | 11 | 12 |
|  7 |  8 |  9 |
|  4 |  5 |  6 |
|  1 |  2 |  3 |

## こんなコードを書いたとする

でも、実行してみたら結果がおかしい……

```{r}
#| echo: true
max_of_3rd_col <-
  \(csv_text = "10,11,12\n7,8,9\n4,5,6\n1,2,3") {
    dat <- read.csv(text = csv_text)
    mx <- max(dat[[3]])
    return(mx)
  }

max_of_3rd_col() # なぜか結果が9になる
```


## どこがおかしいのか当たりをつける

こんなときは、こういうことをする

``` r
debug(max_of_3rd_col)

max_of_3rd_col()

undebug(max_of_3rd_col)
```

## どうおかしいのか当たりをつける

- 修正したいコードに試しに小さなデータを与えて実行してみる
  - ここでは`read.csv(header = FALSE)`とする必要があるっぽい

## まとめ

- Rのコードを書いていて「何をどう調べたらいいかわからない」ときは、まず、どこを直せばよさそうかはわかる（具体的にどう直せばいいかがわからない）という状況をめざそう
- 具体的にどう直せばいいかが自分で調べてもわからなそうなら、AIや人に質問してみよう
